[tool.poetry]
name = "leases"
version = "0.1.0"
description = ""
authors = ["Oliver Treichel <oliver.treichel@gmx.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
kubernetes = "^33.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
